name: ci
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install zc.buildout
        run: pip install zc-buildout
      - name: Run buildout
        run: buildout
